### ISSUE TITLE
Missing license file

### ISSUE THREAD

**Issue by jamesiri** [aws-robotics/kinesisvideo-encoder-common#19]
In order to comply with the LGPLv2.1 license you must provide a copy of the license, not just a link.

**Comment by raghaprasad** [comment]
We do provide a copy : https://github.com/aws-robotics/kinesisvideo-encoder-common/blob/master/h264_encoder_core/LICENSE.txt


Its inside the folder which contains the code for h264_encoder_node. 
Let me know if this needs to be moved. Closing this issue for now.

**Comment by raghaprasad** [comment]
>  licenses should be specified in subfolders and the readme should state that they are individually licensed. But if they are under the same license, you should move a copy of the license to the root directory

This is @jamesiri  recommendation

**Comment by jamesiri** [comment]
If the sub-packages are under the same license then the license should be bubbled to the root directory. Otherwise, stating the sub-packages are independently licensed need to be state in the rood directory of a LICENSE.md file.

**Comment by nburek** [comment]
@jamesiri I've created a new PR to move the license file up to the root directory. If you could take a look to make sure I understood the ask correctly I would appreciate it. 
https://github.com/aws-robotics/kinesisvideo-encoder-common/pull/22
