### ISSUE TITLE
Not grabbing subscribe topic from config

### ISSUE THREAD

**Issue by Gil401** [aws-robotics/kinesisvideo-encoder-common#20]
Hi Guys,

It seems that you are not pulling the subscribe topic from the config.yaml

https://github.com/aws-robotics/kinesisvideo-encoder-common/blob/master/h264_encoder_core/src/h264_encoder_node_config.cpp
line 39

Thanks,

**Comment by raghaprasad** [comment]
@Gil401 Thanks for identifying this issue.  We will update this ticket with a correction shortly.
